version: '3.4'
services:
    calendar-backend:
        restart: always
        image: ghcr.io/dimaip/calendar-backend:master
        hostname: 'calendar-backend'
        networks:
            - main
        ports:
            - '80'
        labels:
            - 'traefik.enable=true'
            - 'traefik.port=80'
            - 'traefik.default.protocol=http'
            - 'traefik.docker.network=main'
            - 'traefik.frontend.rule=Host:api.c.psmb.ru'
networks:
    main:
        external:
            name: main
